# services:

#   broker:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: cc7261:pyzmq
#     container_name: broker
#     volumes:
#       - ./broker.py:/app/main.py
#     ports:
#       - 5555:5555
#       - 5556:5556

#   servidor:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: cc7261:pyzmq
#     volumes:
#       - ./servidor.py:/app/main.py
#     depends_on:
#       - broker
#     deploy:
#       replicas: 1

#   cliente:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: cc7261:pyzmq
#     volumes:
#       - ./cliente.py:/app/main.py
#     depends_on:
#       - servidor
#     deploy:
#       replicas: 1
services:
  broker:
    build: .
    container_name: broker
    command: python -u broker.py

  servidor1:
    build: .
    container_name: servidor1
    command: python -u servidor.py
    environment:
      SERVER_ID: servidor1
      BROKER_BACKEND_URL: tcp://broker:5556
      DB_PATH: /app/data/server1.db
      PUB_BIND_PORT: 7000
      PEER_SUB_URLS: tcp://servidor2:7000
    depends_on:
      - broker
    volumes:
      - data_server1:/app/data

  servidor2:
    build: .
    container_name: servidor2
    command: python -u servidor.py
    environment:
      SERVER_ID: servidor2
      BROKER_BACKEND_URL: tcp://broker:5556
      DB_PATH: /app/data/server2.db
      PUB_BIND_PORT: 7000
      PEER_SUB_URLS: tcp://servidor1:7000
    depends_on:
      - broker
    volumes:
      - data_server2:/app/data

  cliente1:
    build: .
    container_name: cliente1
    command: python -u cliente.py
    environment:
      CLIENT_ID: bot_alpha
      BROKER_URL: tcp://broker:5555
      AUTO_CHANNEL: geral
      STARTUP_DELAY: 5
      STEP_DELAY: 1
    depends_on:
      - broker
      - servidor1
      - servidor2

  cliente2:
    build: .
    container_name: cliente2
    command: python -u cliente.py
    environment:
      CLIENT_ID: bot_beta
      BROKER_URL: tcp://broker:5555
      AUTO_CHANNEL: projetos
      STARTUP_DELAY: 7
      STEP_DELAY: 1
    depends_on:
      - broker
      - servidor1
      - servidor2

volumes:
  data_server1:
  data_server2: